main: community.hlresort.holomatsuri.pointCounter
name: PointCounter
api-version: 1.16
version: 1.0
build: 1

commands:
  setarea:
    description: Set the new build area
    usage: /setarea
    permission: holomatsuricounter.admin
  getarea:
      description: Get the current build area
      usage: /getarea
      permission: holomatsuricounter.admin

  addchest:
    description: Add a tracked chest
    usage: /addchest
    permission: holomatsuricounter.admin
  removechest:
      description: Remove a tracked chest
      usage: /removechest
      permission: holomatsuricounter.admin

  points:
    description: Get your point count
    usage: /points
    permission: holomatsuricounter.player